name: SWIlarge-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - jupyter
  - ipython
  - numpy
  - scipy
  - matplotlib
  - mkl
  - discretize
  - pandas
  - xlrd
  - flopy
  - cartopy
  - mplleaflet
  - pyproj
  - pyshp
  - lightgbm
  - SimPEG==0.13.1
  # - gcc
    - pip:
         - git+https://github.com/simpeg/simpegEM1D.git@master
